// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPv_k2k0sj_5s8RTfHVqA7vRbAvJviE5o',
    appId: '1:351215136507:web:7fd43db764a83c706e8a5e',
    messagingSenderId: '351215136507',
    projectId: 'haven-data',
    authDomain: 'haven-data.firebaseapp.com',
    storageBucket: 'haven-data.firebasestorage.app',
    measurementId: 'G-ZP9EZZ4E4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyuQ5QdMMyA7qoOOGhWwzd3eVvJ4ezljo',
    appId: '1:351215136507:android:5cedc97ed1a9a6de6e8a5e',
    messagingSenderId: '351215136507',
    projectId: 'haven-data',
    storageBucket: 'haven-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc0MF8vYZYOs6-Tic82HaVIJxFGUXKVew',
    appId: '1:351215136507:ios:e0c2e4f39cc9dbe26e8a5e',
    messagingSenderId: '351215136507',
    projectId: 'haven-data',
    storageBucket: 'haven-data.firebasestorage.app',
    iosBundleId: 'com.example.havenV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc0MF8vYZYOs6-Tic82HaVIJxFGUXKVew',
    appId: '1:351215136507:ios:e0c2e4f39cc9dbe26e8a5e',
    messagingSenderId: '351215136507',
    projectId: 'haven-data',
    storageBucket: 'haven-data.firebasestorage.app',
    iosBundleId: 'com.example.havenV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPv_k2k0sj_5s8RTfHVqA7vRbAvJviE5o',
    appId: '1:351215136507:web:f1fe9a915aefd06a6e8a5e',
    messagingSenderId: '351215136507',
    projectId: 'haven-data',
    authDomain: 'haven-data.firebaseapp.com',
    storageBucket: 'haven-data.firebasestorage.app',
    measurementId: 'G-10695N4P25',
  );
}
